import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Knight from "../components/Piece/Knight";
import Board from "../components/Board";
import React from "react";
const Home: NextPage = () => {
  return (
    <div className="flex items-center justify-center bg-gray-500 h-screen w-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-[640px] h-[640px]">
        <Board />
      </div>
    </div>
  );
};

export default Home;
